import MainChat from './MainChat'
import MainContact from './MainContact'
import RegisterPage from './RegisterPage'
import LandingPage from './LandingPage'
import LoginPage from './LoginPage'
import Account from './Account'
import CreatePostPage from './CreatePostPage'
import StorePage from './StorePage'
import LocationPage from './LocationPage'
import VotePage from './VotePage'
import PostPage from './PostsPage/PostPage'
import PostDetailPage from './PostDetailPage'
import ArticalPage from './ArticalPage'

export { MainChat, MainContact, ArticalPage, LandingPage, RegisterPage, LoginPage, Account, CreatePostPage, StorePage, LocationPage, VotePage, PostPage, PostDetailPage }